language: java
jdk:
  - oraclejdk8

before_script:
  - nvm install 0.11
  - nvm use 0.11
  - npm install -g bower gulp
  - cd todo-angularjs && npm install
  - bower install

script:
  - gulp unitTest
